### ISSUE TITLE
npm start issues

### ISSUE THREAD

**Issue by DomDale** [expressjs/generator#106]
I have set up the whole thing up to when you type npm start but when I do I get these errors:
> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/alexavoiceserviceexamples/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/pi/alexvoiceserviceexamples/samples/javaclient/certs/server/node.key'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/pi/alexavoiceserviceexamples/samples/companionService/bin/www:21:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)

npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alexa-voice-service-sample-companion-service
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls alexa-voice-service-sample-companion-service
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/alexavoiceserviceexamples/samples/companionService/npm-debug.log

My debug log is:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: alexa-voice-service-sample-companion-service@1.0.0
6 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: alexa-voice-service-sample-companion-service@1.0.0
8 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/alexavoiceserviceexamples/samples/companionService/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/l$
10 verbose lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: CWD: /home/pi/alexavoiceserviceexamples/samples/companionService
11 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle alexa-voice-service-sample-companion-service@1.0.0~start: Failed to exec start script
14 verbose stack Error: alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid alexa-voice-service-sample-companion-service@1.0.0
16 verbose cwd /home/pi/alexavoiceserviceexamples/samples/companionService
17 error Linux 4.1.19-v7+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v5.9.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error alexa-voice-service-sample-companion-service@1.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the alexa-voice-service-sample-companion-service@1.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the alexa-voice-service-sample-companion-service package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs alexa-voice-service-sample-companion-service
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls alexa-voice-service-sample-companion-service
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Hope someone can help!

**Comment by dougwilson** [comment]
Hi! Looks like this error is from something you have modified from the base generated template. Can you paste your entire `bin/www` file here so we can see what the contents are? It looks like from the error you are trying to read the file `/home/pi/alexvoiceserviceexamples/samples/javaclient/certs/server/node.key` from line 21, but that files does not exist.

**Comment by DomDale** [comment]
I don't have a www file? :P

**Comment by dougwilson** [comment]
It's in the `bin` folder. The full path is also in your error: `/home/pi/alexavoiceserviceexamples/samples/companionService/bin/www`

**Comment by DomDale** [comment]
Oh sorry thought you meant from root directory.

#!/usr/bin/env node

console.log('This node service needs to be running to store token information memory and vend them for the AVS app.\n');

/**
 * Module dependencies.
 */
var app = require('../app');
var debug = require('debug')('companion:server');
var https = require('https');
var fs = require('fs');
var config = require("../config");

/**
 * Get port from environment and store in Express.
 */
var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

var options = {
    key: fs.readFileSync(config.sslKey),
    cert: fs.readFileSync(config.sslCert),
    ca: fs.readFileSync(config.sslCaCert),
    requestCert: true,
    rejectUnauthorized: false,
};

/**
 * Create HTTP server.
 */
var server = https.createServer(options, app);

/**
 * Listen on provided port, on all network interfaces.
 */
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */
function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

**Comment by dougwilson** [comment]
Thanks! Yea, it looks like that file was modified from what we generated. I don't have much more information about your error more than I said in https://github.com/expressjs/generator/issues/106#issuecomment-203029835 You just need to create the files for SSL that your code needs and you should be all-set.

If you still are confused or need help, please drop by our support channel: https://gitter.im/expressjs/express :)

**Comment by DomDale** [comment]
Wait sorry about this. Thought I was posting an issue on https://github.com/amzn/alexa-avs-raspberry-pi/issues ??!?
