### ISSUE TITLE
How to install an app made with this globally / prepare for publication on npm?

### ISSUE THREAD

**Issue by Kezzsim** [expressjs/generator#208]
I recently used this generator to bootstrap / prototype an app with a basic webserver and a bunch of other node processes. It ended up being a single page app that doesn't depend on the more advanced templating & routing features of express, but certainly makes good use of it's capabilities as a server.

Anyways, this app is somewhat of a special use case in comparison to normal express apps; instead of deploying to Heroku or bundling to WebPack I'd like to make it something people can put on their machines with `npm install` and thusly I've tried to test that functionality by running `npm install -g` and then for development purposes, `npm link`.

By adding ```"bin": {
    "./bin/www"
  }```  I've been able to get it to install in a way that I can run it by typing in `app-name {args}`, the problem is however, I want to be able to run the app from _anywhere_ on the machine, just like you'd expect of any other globally installed node app.
Of course my app has some files associated with it, for the webserver to serve and the server itself to use. I have a random generator that uses a text file (_friendsname.txt_) to get values, when I do `npm start` or `app-name` within the app's own folder it works perfectly, but when I run `app-name` from any other directory I get this:

```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'friendsname.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Dictionary.read (/Users/KariBarry/app-name/node_modules/moniker/lib/moniker.js:60:17)
    at Generator.use (/Users/KariBarry/app-name/node_modules/moniker/lib/moniker.js:115:35)
    at /Users/KariBarry/app-name/node_modules/moniker/lib/moniker.js:36:9
    at Array.forEach (<anonymous>)
    at Object.generator (/Users/KariBarry/app-name/node_modules/moniker/lib/moniker.js:35:9)

    at Object.<anonymous> (/Users/KariBarry/app-name/radio.js:9:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
I've noticed if I move that txt file into the directory I start the app from I can get it to run, which would mean that it's running as if `./` is where the app was running from! It does this with other files express has generated, moving them into the place where the command is run from allows it to run but that probably makes it unsuitable to distribute.

How can I make this program install and run globally the same way doing `npm start` works? How can I get the static resources and directories to be accessible from wherever it runs? I've tried adding `*` and direct links to the required directories to my package.json's `file` field but that doesn't seem to do it. Also when I run `npm pack` and open up the tarball, I see the file there, so I know it's being included properly - it's just the app isn't finding it, it's preferring the directory where the command was run from instead.

I'm sure there's a simple explanation for this, and that I'll just have to add some path modifications to the places where files are located / where _www_ is run from; but right now for the life of me I can't seem to figure it out.

Thanks~

**Comment by dougwilson** [comment]
I wish I knew the answer, but I've never done anything like that. It kind of sounds more like a question for npm than here, as otherwise I have no idea how to help :(
