### ISSUE TITLE
Will not install, Using Node.js 12.14.1 (x64)

### ISSUE THREAD

**Issue by M00NL16H7** [expressjs/generator#245]
When i try`npx express-generator` to install expressjs, It gives me this error 

```
#D:\>npx express-generator
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'D:\node_modules\npm\bin\npx-cli.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:686:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

**Comment by dougwilson** [comment]
Hi @M00NL16H7 , unfortunately the error above is an issue with npm itself, and nothing this module can correct. I've never seen such an issue before, either, so not sure how to help. You can always try to re-install Node.js and see if that helps, otherwise you'll want to contact npm support through one of the methods at https://npm.community/

**Comment by M00NL16H7** [comment]
Ok, thank you
