### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by Yasir900aslam** [expressjs/generator#299]
While Generating project using express generator using command  `express /server && cd /server` command as a root user, the application throw the error below.

```
 create : /server/
/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/server'
    at Object.mkdirSync (node:fs:1023:3)
    at Function.sync (/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/node_modules/mkdirp/index.js:71:13)
    at mkdir (/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/bin/express-cli.js:498:10)
    at createApplication (/home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/bin/express-cli.js:181:5)
    at /home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/bin/express-cli.js:472:7
    at /home/yasir/.nvm/versions/node/v15.14.0/lib/node_modules/express-generator/bin/express-cli.js:384:5
    at FSReqCallback.oncomplete (node:fs:183:23) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/server'
}
```

But if I were to create server directory which is empty and init express in that, there is no error.

### Technical Information
1. npm version 7.12.0
2. node version v15.14.0
3. express version 4.16.1

**Comment by elifraha** [comment]
You are getting this error because you are trying to create a folder in the root directory (/). I presume, what you need is a project folder in current directory (**server**) and not root directory (**/server)**. 

Use `express server && cd server`.
