### ISSUE TITLE
Npm start error

### ISSUE THREAD

**Issue by antonnes** [expressjs/generator#39]
Hello, i am experiencing problem when i try to run my app. I install express-generator globally, then run 'express test_app', then 'npm install' in the test app folder and at the and 'npm start'. It is almost the same like this issue  https://github.com/expressjs/generator/issues/31. The difference is that i am using Windows 7 and the error message is generated in the debug log. It looks like this:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart test_app@0.0.1
7 info start test_app@0.0.1
8 verbose unsafe-perm in lifecycle true
9 error Error: spawn ENOENT
9 error     at errnoException (child_process.js:1001:11)
9 error     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
10 error If you need help, you may report this *entire* log,
10 error including the npm and node versions, at:
10 error     <http://github.com/npm/npm/issues>
11 error System Windows_NT 6.1.7601
12 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error cwd C:\work\test_app
14 error node -v v0.10.30
15 error npm -v 1.4.21
16 error syscall spawn
17 error code ENOENT
18 error errno ENOENT
19 verbose exit [ 1, true ]
```

Reinstalled Node.js, but no effect. I have tried the same procedure on two other computers and there was no problem.

**Comment by lsirpa** [comment]
check this manual :) and see how to solve the problem
https://drive.google.com/file/d/0B4-v0059mrAwQTU1dUpQR2hLcEE/view?usp=sharing
