### ISSUE TITLE
Using express.js 4 with socket.io won't start

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/generator#45]
Surprisingly everything works well when doing `node app.js` instead of `npm start`. 
Why is it?

I'm using express 4.2.0 and I've done:

``` bash
express node6 --hogan --ejs 
cd node6
npm install
npm install socket.io
```

I went into the [socket.io docs](http://socket.io/docs/) and I copied and pasted the code of the app.js file overwriting the one created by default. (which contains much more things)
After the pasting it would look like this:

``` javascript
var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server);

server.listen(80);

app.get('/', function (req, res) {
  res.sendfile(__dirname + '/index.html');
});

io.on('connection', function (socket) {
  socket.emit('news', { hello: 'world' });
  socket.on('my other event', function (data) {
    console.log(data);
  });
});
```

It is throwing errors when doing `npm start`.

Why is it?

This is the `dpm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart node6@0.0.1
7 info start node6@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info node6@0.0.1 Failed to exec start script
10 error node6@0.0.1 start: `node ./bin/www`
10 error Exit status 8
11 error Failed at the node6@0.0.1 start script.
11 error This is most likely a problem with the node6 package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node ./bin/www
11 error You can get their info via:
11 error     npm owner ls node6
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error cwd C:\inetpub\wwwroot\node6
15 error node -v v0.10.29
16 error npm -v 1.4.14
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

After running `node ./bin/www` I get this error:

```
C:\inetpub\wwwroot\node6\bin\www:5
app.set('port', process.env.PORT || 3000);
    ^
TypeError: Object #<Object> has no method 'set'
    at Object.<anonymous> (C:\inetpub\wwwroot\node6\bin\www:5:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

The `start` entry of the `package.json` looks like this:

> "start": "node ./bin/www"

**Comment by weishiji** [comment]
Thanks very much. This problem trouble me for a long time

**Comment by geohelou** [comment]
I am working on socket.io in my Nodejs project. I opted for this solution in order to require the io module and send messages via sockets. The problem with it is that whenever you require the io module, you are actually instantiating a new io variable and a new connection binding, which returns the wrong object and io.sockets.connected returns as an empty object. Any thoughts on how to solve this problem ?
